#!/usr/bin/env bun

/**
 * Build-time codegen: reads docs/embed-manifest.yaml, resolves globs,
 * and generates src/generated/embedded-docs.ts with all matched content.
 *
 * Usage:
 *   bun scripts/embed-docs.ts
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, dirname } from "node:path";
import { Glob } from "bun";
import { parseFrontmatter, parseYaml } from "../src/shared.ts";

const MANIFEST_PATH = "docs/embed-manifest.yaml";
const OUTPUT_PATH = "src/generated/embedded-docs.ts";

function toSlug(filePath: string): string {
	// Normalize path separators first (Windows compat: Bun.Glob returns backslashes)
	const normalized = filePath.replace(/\\/g, "/");
	// Strip first segment (docs/ or content/) and .md extension
	const withoutPrefix = normalized.replace(/^[^/]+\//, "");
	const withoutExt = withoutPrefix.replace(/\.md$/, "");
	const base = basename(withoutExt).toLowerCase();
	if (base === "readme" || base === "index") {
		return dirname(withoutPrefix).replace(/\\/g, "/");
	}
	return withoutExt;
}

function extractTitle(body: string): string {
	for (const line of body.split("\n")) {
		const m = line.match(/^#\s+(.+)/);
		if (m) return m[1].trim();
	}
	return "(untitled)";
}

async function resolveGlobs(includes: string[], excludes: string[]): Promise<string[]> {
	const matched = new Set<string>();

	for (const pattern of includes) {
		const glob = new Glob(pattern);
		for await (const path of glob.scan({ cwd: ".", dot: false })) {
			matched.add(path);
		}
	}

	for (const pattern of excludes) {
		const glob = new Glob(pattern);
		for await (const path of glob.scan({ cwd: ".", dot: false })) {
			matched.delete(path);
		}
	}

	return [...matched].sort();
}

function escapeForTemplate(s: string): string {
	return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

async function main(): Promise<void> {
	const raw = readFileSync(MANIFEST_PATH, "utf-8");
	const manifest = parseYaml(raw);
	const includes = manifest.include as string[];
	const excludes = (manifest.exclude as string[]) ?? [];

	if (!includes?.length) {
		console.error(`Error: no include patterns in ${MANIFEST_PATH}`);
		process.exit(1);
	}

	const files = await resolveGlobs(includes, excludes);

	if (files.length === 0) {
		console.error("Error: no files matched the manifest patterns");
		process.exit(1);
	}

	const entries: Array<[string, string, string]> = [];

	for (const file of files) {
		const content = readFileSync(file, "utf-8");
		const { body } = parseFrontmatter(content);
		const trimmed = body.trim();
		const slug = toSlug(file);
		const title = extractTitle(trimmed);
		entries.push([slug, title, trimmed]);
	}

	// Sort by slug for deterministic output
	entries.sort((a, b) => a[0].localeCompare(b[0]));

	const lines = [
		"// AUTO-GENERATED by scripts/embed-docs.ts — do not edit",
		"export const EMBEDDED_DOCS: ReadonlyArray<readonly [string, string, string]> = [",
	];

	for (const [slug, title, content] of entries) {
		lines.push(
			`\t[${JSON.stringify(slug)}, ${JSON.stringify(title)}, \`${escapeForTemplate(content)}\`],`,
		);
	}

	lines.push("];");
	lines.push("");

	mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
	writeFileSync(OUTPUT_PATH, lines.join("\n"));

	console.log(`Embedded ${entries.length} docs into ${OUTPUT_PATH}`);
	for (const [slug, title] of entries) {
		console.log(`  ${slug} — ${title}`);
	}
}

main();
